repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/ambv/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: flake8
  - repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.6
    hooks:
      - id: python-bandit-vulnerability-check
        args: [--skip, "B101", --recursive, clumper]
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.910 # Use the ref you want to point at
  #   hooks:
  #     - id: mypy
  #       args: [--ignore-missing-imports] # Optional: add any arguments here
